package:
  name: wmt-rest
  version: "0.1"

source:
  path: ..

requirements:
  build:
    - setuptools
    - flask
    - flask-sqlalchemy
    - flask-testing
    - flask-login
    - pyyaml
    - passlib
    - standard_names
    - paramiko
    - nose >=1.3

  run:
    - flask
    - flask-sqlalchemy
    - flask-testing
    - flask-login
    - pyyaml
    - passlib
    - standard_names
    - paramiko
    - nose >=1.3

build:
  string: {{ environ.get('BUILD_STR', '') }}
